# A container with all common configurations
common_properties: 
  german: &german
    sens_attr: Gender
    sens_idx: 1
    sens_num: 100
    predict_attr: GoodCustomer
    label_num: 100
    
  credit: &credit
    sens_attr: Age
    sens_idx: 1
    sens_num: 6000
    predict_attr: NoDefaultNextMonth
    label_num: 6000

  bail: &bail
    sens_attr: WHITE
    sens_idx: 0
    sens_num: 100
    predict_attr: RECID
    label_num: 100

  pokec: &pokec
    sens_attr: region
    sens_idx: 1
    sens_num: 200
    predict_attr: I_am_working_in_field
    label_num: 500
    test_idx: False
    
  nba: &nba
    sens_attr: country 
    sens_idx: 1
    sens_num: 50
    predict_attr: SALARY
    label_num: 100
    test_idx: True

  sport: &sport
    sens_attr: race
    sens_idx: 0
    sens_num: 3508
    predict_attr: sport
    label_num: 3508
    train_ratio: 0.6

  occupation: &occupation
    sens_attr: gender
    sens_idx: 0
    sens_num: 6951
    predict_attr: area
    label_num: 6951
    train_ratio: 0.6
  
  synthetic: &syn
    sens_num: 5000
    label_num: 5000
    sens_idx: 1

datasets:
  german:
    <<: *german
  germanA:
    <<: *german

  credit:
    <<: *credit
  creditA:
    <<: *credit
  
  bail:
    <<: *bail
  bailA:
    <<: *bail
  
  pokec_z:
    <<: *pokec
  pokec_n:
    <<: *pokec

  nba:
    <<: *nba

  synthetic: 
    <<: *syn
  syn-1:
    <<: *syn
  syn-2:
    <<: *syn

  sport:
    <<: *sport
  occupation:
    <<: *occupation
